<?xml version="1.0"?>
<package format="3">
  <name>shared_buffer_backend_py</name>
  <version>0.1.0</version>
  <description>Python zero-copy access to shared-memory rosidl buffers.</description>

  <maintainer email="kato.daisuke429@gmail.com">dskkato</maintainer>
  <license>Apache-2.0</license>
  <author email="kato.daisuke429@gmail.com">dskkato</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>shared_buffer</depend>
  <depend>pybind11-dev</depend>
  <depend>python3-dev</depend>
  <depend>rosidl_buffer</depend>
  <exec_depend>rosidl_buffer_py</exec_depend>
  <exec_depend>rpyutils</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>python3-numpy</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>sensor_msgs</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
